
CREATE DATABASE [BMSDB_SS] ON

( NAME = N'BMSDB_FGSSD_1', FILENAME = N'R:\SQLData\BMSDB\BMSDB_FGSSD_1.SS' ), 
( NAME = N'BMSDB_FGSSD_2', FILENAME = N'R:\SQLData\BMSDB\BMSDB_FGSSD_2.SS'  ), 
( NAME = N'BMSDB_FGSSD_3', FILENAME = N'R:\SQLData\BMSDB\BMSDB_FGSSD_3.SS' ), 
( NAME = N'BMSDB_FGSSD_4', FILENAME = N'R:\SQLData\BMSDB\BMSDB_FGSSD_4.SS'  ), 
( NAME = N'BMSDB_FGSSD_5', FILENAME = N'R:\SQLData\BMSDB\BMSDB_FGSSD_5.SS'  ), 
( NAME = N'BMSDB_FGSSD_6', FILENAME = N'R:\SQLData\BMSDB\BMSDB_FGSSD_6.SS' ), 
( NAME = N'BMSDB_FGSSD_7', FILENAME = N'R:\SQLData\BMSDB\BMSDB_FGSSD_7.SS'  ), 
( NAME = N'BMSDB_FGSSD_8', FILENAME = N'R:\SQLDatA\BMSDB\BMSDB_FGSSD_8.SS' ), 

( NAME = N'BMSDB_FG1_1', FILENAME = N'G:\SQLData\BMSDB\BMSDB_FG1_1.SS' ), 
( NAME = N'BMSDB_FG1_2', FILENAME = N'H:\SQLData\BMSDB\BMSDB_FG1_2.SS' ), 
( NAME = N'BMSDB_FG1_3', FILENAME = N'I:\SQLData\BMSDB\BMSDB_FG1_3.SS' ), 
( NAME = N'BMSDB_FG1_4', FILENAME = N'J:\SQLData\BMSDB\BMSDB_FG1_4.SS'  ), 
( NAME = N'BMSDB_FG1_5', FILENAME = N'K:\SQLData\BMSDB\BMSDB_FG1_5.SS'  ), 
( NAME = N'BMSDB_FG1_6', FILENAME = N'L:\SQLData\BMSDB\BMSDB_FG1_6.SS' ), 
( NAME = N'BMSDB_FG1_7', FILENAME = N'M:\SQLData\BMSDB\BMSDB_FG1_7.SS'  ), 
( NAME = N'BMSDB_FG1_8', FILENAME = N'N:\SQLData\BMSDB\BMSDB_FG1_8.SS'  ), 

( NAME = N'BMSDB_FG2_1', FILENAME = N'G:\SQLData\BMSDB\BMSDB_FG2_1.SS'  ), 
( NAME = N'BMSDB_FG2_2', FILENAME = N'H:\SQLData\BMSDB\BMSDB_FG2_2.SS'  ), 
( NAME = N'BMSDB_FG2_3', FILENAME = N'I:\SQLData\BMSDB\BMSDB_FG2_3.SS'  ), 
( NAME = N'BMSDB_FG2_4', FILENAME = N'J:\SQLData\BMSDB\BMSDB_FG2_4.SS'), 
( NAME = N'BMSDB_FG2_5', FILENAME = N'K:\SQLData\BMSDB\BMSDB_FG2_5.SS' ), 
( NAME = N'BMSDB_FG2_6', FILENAME = N'L:\SQLData\BMSDB\BMSDB_FG2_6.SS' ), 
( NAME = N'BMSDB_FG2_7', FILENAME = N'M:\SQLData\BMSDB\BMSDB_FG2_7.SS'  ), 
( NAME = N'BMSDB_FG2_8', FILENAME = N'N:\SQLData\BMSDB\BMSDB_FG2_8.SS' )
 AS SNAPSHOT OF [BMSDB]