--DELTE DUPLICATE RECORD
DELETE FROM ODSDB.ODSDBA.ODS_UN_UNICMP
WHERE SEQ1+MACMPNY+MACMPNY IN(
SELECT MAX(SEQ1),MACMPNY,RLCMPNY FROM ODSDB.ODSDBA.ODS_UN_UNICMP
WHERE UPPER(MACMPNY)+UPPER(RLCMPNY) IN(
SELECT UPPER(MACMPNY)+UPPER(RLCMPNY)
FROM ODSDB.ODSDBA.ODS_UN_UNICMP
GROUP BY UPPER(MACMPNY)+UPPER(RLCMPNY)
HAVING COUNT(1) > 1 )
GROUP BY MACMPNY,RLCMPNY)