ALTERDATABASE DemoSuspect SET EMERGENCY;

ALTER DATABASE DemoSuspect SET SINGLE_USER;

DBCC CHECKDB (DemoSuspect, REPAIR_ALLOW_DATA_LOSS) 
WITH NO_INFOMSGS, ALL_ERRORMSGS;

ALTER DATABASE DemoSuspect SET MULTI_USER;
