
--------------------------------------------------
CREATE TABLE #TEMP (TABLE_NAME VARCHAR(100))
INSERT INTO #TEMP VALUES 
('BMS_OD_BACTRL'),('BMS_OD_BAITEM'),('BMS_OD_BALIST'),('BMS_OD_FCCTRL'),('BMS_OD_FCITEM'),('BMS_OD_FCLIST'),
('BMS_OD_FCRETURN'),('BMS_OD_FCRETURN_ITEM'),('BMS_OD_LOOKUP_LOG'),('BMS_OD_TEMP'),('BMS_OD_TEMP_ITEM'),('BMS_OD_TEMP_LIST'),
('BMS_OT_LOOKUP_CODE'),
('BMS_RM_BAD_DEBT_BATCH'),('BMS_RM_BAD_DEBT_DETAIL'),('BMS_RM_BILL_INFO'),('BMS_RM_BOX'),('BMS_RM_DELIVERY_INFO'),
('BMS_RM_DELIVERY_STATUS'),('BMS_RM_FORCE_EX_BATCH'),('BMS_RM_FORCE_EX_DETAIL'),('BMS_RM_INQUIRY_HISTORY'),('BMS_RM_MAIL_CD'),
('BMS_RM_MAIL_IMG'),('BMS_RM_RECEIPT_DUP'),('BMS_RM_RECEIPT_IMG'),
('BMS_TL_DETAIL'),('BMS_TL_DIFF'),
('BMS_VL_BILL'),('BMS_VL_BILL_DETAIL'),('BMS_VL_CHARGE_INFO'),('BMS_VL_DETAIL'),('BMS_VL_INVOICE_MASTER'),
('BMS_VL_LOG'),('BMS_VL_PAYMENT'),('BMS_VL_REPAY'),('BMS_VL_WOF'),
('BMS_VT_MASTER'),('BMS_VT_TRANS_DETAIL')
--DROP TABLE #TEMP

CREATE TABLE #SLFF_TABLE_COL (TABLE_NAME VARCHAR(100), COLUMN_NAME VARCHAR(100), COMMENTS VARCHAR(512), DATA_TYPE VARCHAR(20), DATA_LENGHT INT, NULLABLE CHAR(1))

DECLARE cur1 CURSOR FAST_FORWARD FOR SELECT TABLE_NAME FROM #TEMP ORDER BY 1
DECLARE @TABLE_NAME VARCHAR(100)

OPEN cur1
FETCH NEXT FROM cur1 INTO @TABLE_NAME
WHILE @@FETCH_STATUS=0
BEGIN
   INSERT INTO #SLFF_TABLE_COL
   EXEC ('SELECT A.TABLE_NAME, A.COLUMN_NAME, B.COMMENTS, A.DATA_TYPE, A.DATA_LENGTH, A.NULLABLE    
          FROM USER_TAB_COLUMNS A    
              INNER JOIN USER_COL_COMMENTS B ON A.TABLE_NAME=B.TABLE_NAME AND A.COLUMN_NAME=B.COLUMN_NAME
          WHERE A.TABLE_NAME=? ORDER BY A.COLUMN_ID', @TABLE_NAME) AT [ETCDB]      

   FETCH NEXT FROM cur1 INTO @TABLE_NAME
END

CLOSE cur1 ; DEALLOCATE cur1

DROP TABLE #TEMP

SELECT * FROM #SLFF_TABLE_COL
