create table #test
(
STRING VARCHAR(1000)
)

bulk insert #test
from 'D:\CRM\FMT\FD_PBMR.FMT'

declare @TABLE_NAME VARCHAR(128)
SET @TABLE_NAME='ODS_UN_PBMR'

SELECT CAST(ISMD.DBO.INSTR(S1.STRING,'	',6) AS INT) AS SEQ
,ISMD.DBO.INSTR(S1.STRING,'	',4) AS COL_LEN
,CASE WHEN S4.NAME IN ('CHAR','NCHAR','VARCHAR','NVARCHAR') THEN 's'
      WHEN S4.NAME IN ('DECIMAL','NUMERIC','INT','SMALLINT','BIGINT','FLOAT') THEN 'n'
      WHEN S4.NAME IN ('DATETIME','SMALLDATETIME') THEN 'd' ELSE '' END+
ISMD.DBO.INSTR(S1.STRING,'	',7) AS COL_NAME1 
,S4.NAME AS TYPE
INTO #SQL_STR 
FROM #TEST S1
LEFT JOIN ODSDB.dbo.SYSOBJECTS S2 ON S2.NAME=@TABLE_NAME AND S2.TYPE='U'
LEFT JOIN ODSDB.dbo.SYSCOLUMNS S3 ON S2.ID=S3.ID AND ISMD.DBO.INSTR(S1.STRING,'	',7)=S3.NAME
LEFT JOIN ODSDB.dbo.SYSTYPES S4 ON S3.XTYPE=S4.XTYPE
WHERE ISMD.DBO.INSTR(S1.STRING,'	',4) IS NOT NULL AND CAST(ISMD.DBO.INSTR(S1.STRING,'	',6) AS INT)<>0
ORDER BY SEQ


DECLARE @QT_ST INT,@QT_END INT
DECLARE @SQL VARCHAR(MAX)
DECLARE @COL_LEN VARCHAR(10),@COL_NAME VARCHAR(128)
SET @QT_ST=1
SET @SQL='SELECT '
WHILE @QT_ST<=(SELECT COUNT(*) FROM #SQL_STR)
  BEGIN
    SELECT @COL_LEN=COL_LEN,@COL_NAME=COL_NAME1 FROM #SQL_STR WHERE SEQ=@QT_ST
    SET @SQL=@SQL+'CAST('' '' AS CHAR('+@COL_LEN+')) AS '+@COL_NAME+','
    SET @QT_ST=@QT_ST+1
  END

SET @SQL=SUBSTRING(@SQL,1,LEN(@SQL)-1)
PRINT @SQL


DROP TABLE #TEST
DROP TABLE #SQL_STR