  --每個LINE,GEN的啟用日期
  CREATE TABLE #LINE2GEN (SEQ INT,LINE_ID NCHAR(20),GEN_SIZE NCHAR(10),CYCLE_TIME DECIMAL(4,1),ACTIVATE_DATE DATETIME);

  INSERT INTO #LINE2GEN (SEQ,LINE_ID,GEN_SIZE,CYCLE_TIME,ACTIVATE_DATE)
  SELECT   ROW_NUMBER() OVER (PARTITION BY LINE_ID,GEN_SIZE ORDER BY ACTIVATE_DATE) AS SEQ
          ,RTRIM(LINE_ORIENTATION)+RTRIM(LINE_ID)
          ,GEN_SIZE
          ,CYCLE_TIME
          ,ACTIVATE_DATE
  FROM  (SELECT DISTINCT LINE_ID
		,(Case When ETLMD.dbo.INSTR(GEN_SIZE,'.',2)=0 Then cast(ETLMD.dbo.INSTR(GEN_SIZE,'.',1) as varchar(10)) Else cast(GEN_SIZE as varchar(10)) End) AS GEN_SIZE
		,LINE_ORIENTATION
		,CYCLE_TIME
		,ACTIVATE_DATE 
         FROM  ODSDB.DIMES.ODS_DIMES_SPM_CYCLE_TIME_RECORD) S1
  ORDER BY LINE_ID,GEN_SIZE;  
 
---------------------------------------------------
-- PART 3: CREATE TEMP TABLE(GENERATE Expire_Date)
--------------------------------------------------
  
  CREATE TABLE #ODS_DIMES_SPM_CYCLE_TIME_RECORD (LINE_ID NCHAR(20),GEN_SIZE NCHAR(10),CYCLE_TIME DECIMAL(4,1),Effective_Date DATETIME,Expire_Date DATETIME);  
  
  INSERT INTO #ODS_DIMES_SPM_CYCLE_TIME_RECORD
  SELECT S1.LINE_ID,S1.GEN_SIZE,S1.CYCLE_TIME,S1.ACTIVATE_DATE,CASE WHEN S2.ACTIVATE_DATE IS NULL THEN '9999/01/01' ELSE DATEADD(MI,-1,S2.ACTIVATE_DATE) END AS Expire_Date 
  FROM  #LINE2GEN S1
   LEFT OUTER JOIN #LINE2GEN S2 ON (S1.SEQ + 1 = S2.SEQ AND S1.LINE_ID=S2.LINE_ID AND S1.GEN_SIZE=S2.GEN_SIZE)
