DECLARE @DATACAT CHAR(10)
SET @DATACAT = 'ODRDBD'

SELECT DISTINCT UPPER( CASE WHEN S2.UN_FG = 'Y' THEN 'ODS_UN_'+ SUBSTRING( RTRIM(dbo.INSTR(S1.JOB_NAME,'_',2)), 3, LEN(RTRIM(dbo.INSTR(S1.JOB_NAME,'_',2) ))-2) ELSE 'ODS_'+LEFT(S1.JOB_STAGE,LEN(RTRIM(S1.JOB_STAGE))-1)+ '_'+SUBSTRING( RTRIM(dbo.INSTR(S1.JOB_NAME,'_',2)), LEN(RTRIM(S1.JOB_STAGE)),LEN(RTRIM(dbo.INSTR(S1.JOB_NAME,'_',2))) - LEN(RTRIM(S1.JOB_STAGE))+1 ) END) AS NAME
FROM ODSDBA.XJOBDETAIL S1
    ,ODSDBA.XFLOWDETAIL S2
WHERE S2.DATACAT = S1.DATACAT
 AND LEFT(S1.JOB_NAME,3) = 'IS_'
 AND S1.DATACAT =  @DATACAT
UNION ALL 
SELECT UPPER(CASE WHEN S2.UN_FG = 'Y' THEN 'ODSMS_UN_'+RIGHT(DBO.INSTR(JOB_NAME,'_',3),LEN(DBO.INSTR(JOB_NAME,'_',3))-7)
            ELSE 'ODSMS_'+LEFT(S1.JOB_STAGE,LEN(RTRIM(S1.JOB_STAGE))-1)+'_'+RIGHT(DBO.INSTR(JOB_NAME,'_',3),LEN(DBO.INSTR(JOB_NAME,'_',3))-LEN('ODSMS_'+LEFT(S1.JOB_STAGE,LEN(RTRIM(S1.JOB_STAGE))-1))+1) END)
FROM ISMD.ODSDBA.XJOBDETAIL S1
    ,ISMD.ODSDBA.XFLOWDETAIL S2
WHERE S2.DATACAT=S1.DATACAT
 AND LEFT(S1.JOB_NAME,12) = 'SP_INS_ODSMS'
 AND S2.DATACAT = @DATACAT
UNION ALL
SELECT DISTINCT UPPER(CASE WHEN JOB_NAME LIKE '%FB_RTBALDP_DH%' THEN 'FB_RTBALDP_DH' WHEN JOB_NAME LIKE '%FB_NUMWK_DH%' THEN 'FB_NUMWK_DH' ELSE REPLACE(JOB_NAME,'SP_','') END)
FROM ISMD.ODSDBA.XJOBDETAIL S1
WHERE (S1.JOB_NAME LIKE 'SP_TX_%' OR JOB_NAME LIKE 'SP_FB_%') 
 AND S1.DATACAT = @DATACAT
