9.0
17
1	SQLCHAR	0	15	"\",,\""	1	TX_ORDER           Chinese_Taiwan_Stroke_CI_AS
2	SQLCHAR	0	8	"\",,\""	2	MON_FILE_NAME      Chinese_Taiwan_Stroke_CI_AS
3	SQLCHAR	0	8	"\",,\""	3	MON_START_YMD      Chinese_Taiwan_Stroke_CI_AS
4	SQLCHAR	0	8	"\",,\""	4	MON_STOP_YMD       Chinese_Taiwan_Stroke_CI_AS
5	SQLCHAR	0	4	"\",,\""	5	MON_TELL           Chinese_Taiwan_Stroke_CI_AS
6	SQLCHAR	0	4	"\",,\""	6	MON_DEPKIND        Chinese_Taiwan_Stroke_CI_AS
7	SQLCHAR	0	9	"\",,\""	7	MON_ACNO           Chinese_Taiwan_Stroke_CI_AS
8	SQLCHAR	0	7	"\",,\""	8	MON_TX_YMD         Chinese_Taiwan_Stroke_CI_AS
9	SQLCHAR	0	4	"\",,\""	9	MON_TX_SEQ         Chinese_Taiwan_Stroke_CI_AS
10	SQLCHAR	0	2	"\",,\""	10	MON_MEMO           Chinese_Taiwan_Stroke_CI_AS
11	SQLCHAR	0	7	"\",,\""	11	MON_CKNO           Chinese_Taiwan_Stroke_CI_AS
12	SQLCHAR	0	13	"\",,\""	12	MON_AMT            Chinese_Taiwan_Stroke_CI_AS
13	SQLCHAR	0	13	"\",,\""	13	MON_BAL            Chinese_Taiwan_Stroke_CI_AS
14	SQLCHAR	0	4	"\",,\""	14	MON_MGR            Chinese_Taiwan_Stroke_CI_AS
15	SQLCHAR	0	1	"\",,\""	15	MON_DR_CR          Chinese_Taiwan_Stroke_CI_AS
16	SQLCHAR	0	1	"\",,\""	16	MON_CARD_ONLY      Chinese_Taiwan_Stroke_CI_AS
17	SQLCHAR	0	1	"\",,\"\r\n"	17	MON_BOOK_ONLY      Chinese_Taiwan_Stroke_CI_AS


1",,"MONTHMTR",,"20030101",,"20030131",,"0100",,"0101",,"000000171",,"0920106",,"0001",,"CI",,"0317454",,"0000000040000",,"0000025589134",,"0000",,"C",," ",," ",,"
2",,"MONTHMTR",,"20030101",,"20030131",,"0198",,"0101",,"000000171",,"0920110",,"0001",,"TE",,"2227689",,"0000000026200",,"0000025562934",,"0000",,"D",," ",," ",,"


8.0
5
1 SQLCHAR 0 0 "\"" 0 Quote  SQL_LATIN1_GENERAL_CP1_CI_AS
2 SQLCHAR 0 0 "\",\"" 1 QuotedStr1 SQL_LATIN1_GENERAL_CP1_CI_AS
3 SQLCHAR 0 0 "\"," 2 QuotedStr2 SQL_LATIN1_GENERAL_CP1_CI_AS
4 SQLCHAR 0 0 ",\"" 3 Unquotedstr1 SQL_LATIN1_GENERAL_CP1_CI_AS
5 SQLCHAR 0 0 "\"\r\n" 4 Quotedstr3 SQL_LATIN1_GENERAL_CP1_CI_AS


And the BCPtstdata.txt file is

"Str1A","Str2A",NoQuotesA,"Str3A"
"Str1B","Str2B",NoQuotesB,"Str3B"
